// src/app/layout.tsx
import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Top from "@/components/layout/Top";
import { AuthProvider } from '@/context/AuthContext'; // AuthProvider 임포트

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: React.PropsWithChildren<{}>) {
  return (
    <html lang="en">
      <body className="w-full h-[100vh]">
        <div className="w-full h-full">
          <AuthProvider> {/* AuthProvider로 children을 감쌉니다. */}
            <Top />
            {children}
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
